Repository ascendia-network/airdao-mobile, pull requests merged in 2025-04, with the labels that each got.

#1147 Fix: Solve issues with RPC Methods & product titles case sensitivity ignored
  src/features/browser/lib/rpc-middleware.ts
  src/features/browser/types/rpc-methods.types.ts
  src/features/products/components/base/product-list-item/index.tsx
  src/features/products/components/templates/products-list/index.tsx
  src/features/products/entities/_products.tsx
Labels: enhancement

#1150 feat: add KeyboardAvoidingView to BrowserScreen for better keyboard handling on Android
  src/screens/Browser/index.tsx
Labels: enhancement

#1155 Feat: solve minor WebView method issues & wallet connect "unknown" issue
  src/api/explorer-service.ts
  src/features/browser/lib/middleware-helpers/ethBlockCore.ts
  src/features/browser/lib/middleware-helpers/ethTransactionCore.ts
  src/features/browser/lib/middleware-helpers/index.ts
  src/features/browser/lib/middleware-helpers/walletGetPermissions.ts
  src/features/browser/lib/rpc-middleware.ts
  src/features/browser/types/rpc-methods.types.ts
  src/features/wallet-connect/components/composite/wallet-connect-tx-approval/index.tsx
  src/features/wallet-connect/lib/hooks/use-decode-callback.ts
  src/features/wallet-connect/utils/approval-abi.ts
  src/hooks/query/index.ts
  src/hooks/query/useGetTokenDetails.ts
  src/utils/get-token-name-from-db.ts
Labels: enhancement

#1156 feat: enhance token details loading and improve transaction approval handling
  src/features/wallet-connect/components/composite/wallet-connect-tx-approval/index.tsx
  src/features/wallet-connect/lib/hooks/use-decode-callback.ts
Labels: bug, enhancement

#1157 feat: enhance token details loading and improve transaction approval handling
  src/features/wallet-connect/components/composite/wallet-connect-tx-approval/index.tsx
  src/features/wallet-connect/lib/hooks/use-decode-callback.ts
Labels: bug, enhancement

#1160 feat: integrate Sentry for error tracking and update environment configuration
  .env.example
  App.tsx
  app.config.js
  env.d.ts
  package.json
  src/features/wallet-connect/lib/wc.core.ts
  src/lib/index.ts
  src/lib/sentry.core.ts
  yarn.lock
Labels: enhancement, dependencies

#1161 refactor: improve token handling in WalletConnectTxApproval and update amount retrieval in useDecodeCallbackData
  src/features/wallet-connect/components/composite/wallet-connect-tx-approval/index.tsx
  src/features/wallet-connect/lib/hooks/use-decode-callback.ts
Labels: enhancement

#1162 fix: improve token handling in WalletConnectTxApproval and update amount retrieval in useDecodeCallbackData
  src/features/wallet-connect/components/composite/wallet-connect-tx-approval/index.tsx
  src/features/wallet-connect/lib/hooks/use-decode-callback.ts
Labels: enhancement

#1164 feat: add GitHub Actions workflow for automatic PR labeling based on commits
  .github/workflows/lint.yml
  .github/workflows/pull-request-label.yml
  .github/workflows/tests.yml
Labels: fix, feature, chore

#1165 feat(rpc-methods): add EthBlockNumber method to RPC middleware and streamline ethGetBlockNumber function
  src/features/browser/lib/middleware-helpers/ethBlockCore.ts
  src/features/browser/lib/rpc-middleware.ts
Labels: feature

#1166 fix(android/webview): prevent rendering WebView component while app is not active
  src/screens/Browser/index.tsx
Labels: enhancement, performance, fix

#1170 feat(swap/tokens): add new cryptocurrency tokens and their logos
  src/appTypes/blockchain/CryptoCurrencyCode.ts
  src/components/modular/TokenLogo/index.tsx
  src/components/svg/icons/TokenBULL.tsx
  src/components/svg/icons/TokenMAGA.tsx
  src/components/svg/icons/TokenMerica.tsx
  src/components/svg/icons/TokenNTC.tsx
  src/components/svg/icons/index.ts
  src/constants/allToken.ts
  src/features/swap/entities/tokens.ts
Labels: enhancement, config

#1171 feat: added handling of browser methods
  package.json
  src/components/composite/BottomSheet/BottomSheet.types.ts
  src/constants/config.ts
  src/features/browser/components/templates/bottom-sheet-approve-browser-action/index.tsx
  src/features/browser/lib/middleware-helpers/ethDecrypt.ts
  src/features/browser/lib/middleware-helpers/ethEncryptionPublicKey.ts
  src/features/browser/lib/middleware-helpers/ethGasPrice.ts
  src/features/browser/lib/middleware-helpers/ethGenericProviderHandler.ts
  src/features/browser/lib/middleware-helpers/index.ts
  src/features/browser/lib/rpc-middleware.ts
  src/features/browser/types/rpc-methods.types.ts
Labels: feature

#1169 feat(browser): integrate audio handler
  src/entities/browser/lib/hooks/index.ts
  src/entities/browser/lib/hooks/use-audio-handler.ts
  src/screens/Browser/index.tsx
Labels: enhancement, refactoring, feature

#1172 config: update config variable for stage environment
  src/constants/config.ts
Labels: config

#1173 Build: Solve minor issues & integrate AMB Rodeo product
  .env.example
  .github/workflows/lint.yml
  .github/workflows/pull-request-label.yml
  .github/workflows/tests.yml
  App.tsx
  app.config.js
  env.d.ts
  package.json
  src/appTypes/blockchain/CryptoCurrencyCode.ts
  src/components/composite/BottomSheet/BottomSheet.types.ts
  src/components/modular/TokenLogo/index.tsx
  src/components/svg/icons/TokenBULL.tsx
  src/components/svg/icons/TokenMAGA.tsx
  src/components/svg/icons/TokenMerica.tsx
  src/components/svg/icons/TokenNTC.tsx
  src/components/svg/icons/index.ts
  src/constants/allToken.ts
  src/constants/config.ts
  src/entities/browser/lib/hooks/index.ts
  src/entities/browser/lib/hooks/use-audio-handler.ts
  src/features/browser/components/templates/bottom-sheet-approve-browser-action/index.tsx
  src/features/browser/lib/middleware-helpers/ethBlockCore.ts
  src/features/browser/lib/middleware-helpers/ethDecrypt.ts
  src/features/browser/lib/middleware-helpers/ethEncryptionPublicKey.ts
  src/features/browser/lib/middleware-helpers/ethGasPrice.ts
  src/features/browser/lib/middleware-helpers/ethGenericProviderHandler.ts
  src/features/browser/lib/middleware-helpers/index.ts
  src/features/browser/lib/rpc-middleware.ts
  src/features/browser/types/rpc-methods.types.ts
  src/features/swap/entities/tokens.ts
  src/features/wallet-connect/lib/wc.core.ts
  src/features/wallet-connect/utils/__tests__/helpers.test.ts
  src/features/wallet-connect/utils/eip155-request.ts
  src/features/wallet-connect/utils/presets.ts
  src/lib/index.ts
  src/lib/sentry.core.ts
  src/screens/Browser/index.tsx
  yarn.lock
Labels: refactoring, fix, config, feature, chore

#1174 build: update app version and configuration settings
  app.config.js
  src/constants/config.ts
Labels: build, config

#1180 feat(swap!): automatically execute DEX tokens from AMB Rodeo & TokenLogo tries to parse logo from rodeo tokens
  Providers.tsx
  src/components/animations/Shimmer/index.tsx
  src/components/base/TokenImageIpfsWithShimmer/index.tsx
  src/components/base/TokenImageIpfsWithShimmer/styles.ts
  src/components/base/index.ts
  src/components/modular/TokenLogo/index.tsx
  src/constants/config.ts
  src/entities/amb-rodeo-tokens/lib/hooks/index.ts
  src/entities/amb-rodeo-tokens/lib/hooks/use-rodeo-tokens-list-query.ts
  src/entities/amb-rodeo-tokens/lib/index.ts
  src/entities/amb-rodeo-tokens/lib/rodeo-tokens.graph.ts
  src/entities/amb-rodeo-tokens/model/index.ts
  src/entities/amb-rodeo-tokens/model/rodeo-tokens.store.ts
  src/entities/amb-rodeo-tokens/types/index.ts
  src/entities/amb-rodeo-tokens/types/token.ts
  src/entities/currencies/lib/hooks/use-currencies-query.ts
  src/features/swap/components/templates/bottom-sheet-tokens-list/index.tsx
  src/features/swap/entities/tokens.ts
  src/features/swap/lib/hooks/use-all-liquidity-pools.ts
  src/features/swap/lib/hooks/use-swap-all-balances.ts
  src/features/swap/utils/balances.ts
  src/features/swap/utils/index.ts
  src/features/swap/utils/multi-route.ts
  src/features/swap/utils/transform-tokens-object.ts
  src/features/swap/utils/wrap-native-address.ts
  src/lib/apollo/endpoints.ts
  src/lib/apollo/index.ts
  src/lib/apollo/instance.ts
  src/lib/index.ts
  src/screens/Swap/index.tsx
  src/utils/hexlify.ts
  src/utils/index.ts
Labels: fix, feature

#1183 feat(tokens-list-item): enhance token identification logic in TokensListItem component
  src/features/send-funds/components/base/tokens-list-item/index.tsx
Labels: feature
