Repository ascendia-network/airdao-mobile, pull requests merged in 2025-05, with the labels that each got.

#1184 Bridge/network fee fix
  src/constants/config.ts
  src/constants/variables.ts
  src/features/bridge/constants/index.ts
  src/features/bridge/context/Bridge.Context.tsx
  src/features/bridge/templates/BottomSheetBridgePreview/components/GeneralPreviewTemplate/GeneralPreviewTemplate.tsx
  src/features/bridge/templates/BridgeForm/BridgeForm.tsx
  src/features/bridge/templates/BridgeTransaction/index.tsx
  src/features/bridge/utils/getBridgeFee.ts
  src/lib/bridgeSDK/bridgeFunctions/bridgeWithdraw.ts
  src/lib/bridgeSDK/bridgeFunctions/calculateGazFee.ts
  src/lib/bridgeSDK/bridgeFunctions/currentProveder.ts
  src/lib/bridgeSDK/bridgeFunctions/getAllBridgeFees.ts
  src/lib/bridgeSDK/bridgeFunctions/getAllBridgeTransactionFee.ts
  src/lib/bridgeSDK/models/types.ts
  src/lib/bridgeSDK/sdk/index.ts
  src/lib/bridgeSDK/sdk/withdraws.ts
  src/localization/locales/English.json
  src/localization/locales/Turkish.json
  src/models/Bridge.ts
  src/models/dtos/Bridge.ts
  src/screens/SendFunds/index.tsx
Labels: fix, feature

#1185 feat: enhance token loading logic and improve token name retrieval across components
  src/components/base/TokenImageIpfsWithShimmer/index.tsx
  src/components/modular/TokenLogo/index.tsx
  src/components/modular/TokenSelector/index.tsx
  src/components/templates/AccountActions/components/Swap.tsx
  src/features/swap/components/composite/token-selector/index.tsx
  src/features/swap/components/modular/bottom-sheet-token-item/index.tsx
  src/screens/Asset/index.tsx
Labels: feature

#1186 feat: enhance TokenImageIpfsWithShimmer component with improved loading logic and error handling
  src/components/base/TokenImageIpfsWithShimmer/index.tsx
  src/components/modular/TokenLogo/index.tsx
  src/components/templates/AccountActions/components/Swap.tsx
Labels: fix, feature

#1187 feat: add multicall support and enhance balance fetching logic in swap feature
  src/features/swap/components/templates/bottom-sheet-tokens-list/index.tsx
  src/features/swap/lib/abi/MULTICALL.ts
  src/features/swap/lib/contracts/index.ts
  src/features/swap/lib/contracts/multicall.ts
  src/features/swap/lib/hooks/index.ts
  src/features/swap/lib/hooks/use-swap-all-balances.ts
  src/features/swap/utils/index.ts
  src/screens/Swap/index.tsx
Labels: feature

#1188 fix: bridge/dex: resolve bridge network fee issues, add DEX multicall handler & optimize ipfs loading
  src/components/base/TokenImageIpfsWithShimmer/index.tsx
  src/components/modular/TokenLogo/index.tsx
  src/components/modular/TokenSelector/index.tsx
  src/constants/config.ts
  src/constants/variables.ts
  src/features/bridge/constants/index.ts
  src/features/bridge/context/Bridge.Context.tsx
  src/features/bridge/templates/BottomSheetBridgePreview/components/GeneralPreviewTemplate/GeneralPreviewTemplate.tsx
  src/features/bridge/templates/BridgeForm/BridgeForm.tsx
  src/features/bridge/templates/BridgeTransaction/index.tsx
  src/features/bridge/utils/getBridgeFee.ts
  src/features/swap/components/composite/token-selector/index.tsx
  src/features/swap/components/modular/bottom-sheet-token-item/index.tsx
  src/features/swap/components/templates/bottom-sheet-tokens-list/index.tsx
  src/features/swap/lib/abi/MULTICALL.ts
  src/features/swap/lib/contracts/index.ts
  src/features/swap/lib/contracts/multicall.ts
  src/features/swap/lib/hooks/index.ts
  src/features/swap/lib/hooks/use-swap-all-balances.ts
  src/features/swap/utils/index.ts
  src/lib/bridgeSDK/bridgeFunctions/bridgeWithdraw.ts
  src/lib/bridgeSDK/bridgeFunctions/calculateGazFee.ts
  src/lib/bridgeSDK/bridgeFunctions/currentProveder.ts
  src/lib/bridgeSDK/bridgeFunctions/getAllBridgeFees.ts
  src/lib/bridgeSDK/bridgeFunctions/getAllBridgeTransactionFee.ts
  src/lib/bridgeSDK/models/types.ts
  src/lib/bridgeSDK/sdk/index.ts
  src/lib/bridgeSDK/sdk/withdraws.ts
  src/localization/locales/English.json
  src/localization/locales/Turkish.json
  src/models/Bridge.ts
  src/models/dtos/Bridge.ts
  src/screens/Asset/index.tsx
  src/screens/SendFunds/index.tsx
  src/screens/Swap/index.tsx
Labels: fix, feature

#1191 feat: add react-native-fast-image for optimized image loading
  package.json
  src/components/base/TokenImageIpfsWithShimmer/index.tsx
  src/components/modular/TokenLogo/index.tsx
  yarn.lock
Labels: feature

#1192 update 1.5.2
  app.config.js
  package.json
  src/components/base/TokenImageIpfsWithShimmer/index.tsx
  src/components/modular/TokenLogo/index.tsx
  src/components/templates/AccountActions/index.tsx
  src/constants/config.ts
  src/features/swap/components/base/bottom-sheet-review-token-item/index.tsx
  src/features/swap/utils/multi-route.ts
  src/screens/SendFunds/components/confirm-tx/index.tsx
  src/screens/SendFunds/index.tsx
  src/screens/Wallets/index.tsx
  src/utils/__tests__/numbers.test.ts
  src/utils/number.ts
  yarn.lock
Labels: refactoring, fix, build, feature

#1199 Merge 'stage' into 'main'
  app.config.js
  src/api/harbor/harbor-service.ts
  src/api/harbor/hbr-yield.service.ts
  src/assets/coinAirDAODict.json
  src/components/templates/AlertModalTemplate/index.tsx
  src/components/templates/AlertModalTemplate/styles.ts
  src/components/templates/index.ts
  src/constants/config.ts
  src/entities/global-error/global-error-store.model.ts
  src/entities/global-error/global-error-store.ts
  src/entities/harbor/constants/index.ts
  src/entities/harbor/model/harbor-store.ts
  src/entities/harbor/model/stake-hbr.store.ts
  src/entities/harbor/model/types.ts
  src/entities/harbor/utils/getAllHarborData.ts
  src/entities/harbor/utils/getHarborToken.ts
  src/entities/harbor/utils/stake-hbr-promise.ts
  src/features/browser/components/modular/browser-header/styles.ts
  src/features/browser/components/templates/bottom-sheet-browser-modal/index.tsx
  src/features/browser/components/templates/bottom-sheet-browser-modal/styles.ts
  src/features/browser/components/templates/browser-modal/index.tsx
  src/features/browser/components/templates/index.ts
  src/features/browser/lib/injectable.provider.ts
  src/features/harbor/components/base/stake-info-container/index.tsx
  src/features/harbor/components/base/tiers-selector/index.tsx
  src/features/harbor/components/base/token-reward/index.tsx
  src/features/harbor/components/composite/critical-error-handler/index.tsx
  src/features/harbor/components/composite/critical-error-handler/showCriticalError.ts
  src/features/harbor/components/tabs/stake-amb-tab/index.tsx
  src/features/harbor/components/tabs/withdraw-reward-only-tab/index.tsx
  src/features/harbor/components/tabs/withdraw-stake-reward-tab/index.tsx
  src/features/harbor/components/templates/bottom-sheet-critical-error/index.tsx
  src/features/harbor/components/templates/bottom-sheet-critical-error/styles.ts
  src/features/harbor/components/templates/harbor-preview/model.ts
  src/features/harbor/components/templates/index.ts
  src/features/harbor/lib/calculateClaimAmount.ts
  src/features/harbor/lib/parseDataHelpers/parseWithdrawReward.ts
  src/features/harbor/lib/parseDataHelpers/parseWithdrawStakePreview.ts
  src/features/products/components/base/product-list-item/index.tsx
  src/features/products/utils/parseWebProduct.tsx
  src/localization/locales/English.json
  src/localization/locales/Turkish.json
  src/navigation/NavigationContainer.tsx
  src/screens/SendFunds/components/confirm-tx/index.tsx
Labels: refactoring, fix, build, feature

#1201 fix: add button in home screen navigation alert to open swap on iOS
  src/components/templates/AccountActions/components/Swap.tsx
Labels: fix

#1200 feat: set default token to list if user does not have one
  src/screens/SendFunds/index.tsx
Labels: feature

#1202 feat: add "Swap" event listener to handle pool reserves updates
  src/constants/config.ts
  src/features/swap/lib/abi/PAIR.ts
  src/features/swap/lib/hooks/index.ts
  src/features/swap/lib/hooks/use-all-liquidity-pools.ts
  src/features/swap/lib/hooks/use-swap-all-balances.ts
  src/features/swap/lib/hooks/use-trade-price-listener.ts
  src/features/swap/utils/wrap-native-address.ts
  src/screens/Swap/index.tsx
Labels: feature

#1204 fix: hide AMB token when user has other tokens
  src/screens/SendFunds/index.tsx
Labels: fix

#1205 fix(countdown): correct days calculation in token unlock timer
  src/features/harbor/components/composite/countdown-timer/index.tsx
Labels: fix
